stages:
  - test

test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y wget gzip
  - ./scripts/install-raku
  - export PERL6LIB=$PWD/lib
  - export PATH=$HOME/.raku/bin:$PATH
  - make test

